### ISSUE TITLE
slightly better default for `refcode_path`   in `xyz_to_cif.py` in the zip.

### ISSUE THREAD

**Issue by kjappelbaum** [arosen93/QMOF#1]
Thanks for this great effort 🔥 , will be really useful for the MOF community 👍 .

In the `zip` on figshare, I think a better default for the `refcode_path` in `/qmof_database/CSD-14204-opt/xyz_to_cifs.cif` would be `CSD-14204-opt-refcodes.csv` ;)

**Comment by arosen93** [comment]
Thanks!!!

Me: Oh god... did I leave something embarrassing in the filepath?
Me: Oh phew, _just_ a typo. 

Damn, thought I caught them all! I'll keep this Issue open until I update Figshare next. Thanks for catching that!

**Comment by arosen93** [comment]
Now resolved in v2 of the QMOF database (currently being uploaded to Figshare).
