### ISSUE TITLE
The code to generate the atom_init.json file is missing 

### ISSUE THREAD

**Issue by YuanbinLiu** [arosen93/QMOF#18]
Dear authors, 

how did you get the _atom_init.json_ file? Is there any available code to generate it?

**Comment by arosen93** [comment]
Hi @YuanbinLiu. Thanks for your question.

First, for details of how the `atom_init.json` file is constructed, please refer to the [the SI of the original CGCNN paper by Xie and Grossman](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.120.145301). It's a vector of one-hot encodings for the different atom features in Table S2 of the original CGCNN paper.

In our work, the `atom_init.json` file was taken from the original CGCNN code [here](https://github.com/txie-93/cgcnn), after which we made some minor modifications as detailed in the SI of the QMOF Database paper based in part on [this comment](https://github.com/txie-93/cgcnn/issues/2). However, I should emphasize that these changes did not have any appreciable effect on the validation MAE of the model. You can almost certainly use the original `atom_init.json` file [here](https://github.com/txie-93/cgcnn/tree/master/data/sample-regression) and get equivalent results.

**Comment by YuanbinLiu** [comment]
Thank you so much! this is really helpful.

**Comment by arosen93** [comment]
No problem! I am going to close the issue, but don't hesitate to comment if you have any additional questions. I also found the `atom_init.json` file of the CGCNN code to be quite cryptic the first time I saw it, but once you try and compare it to Table S2, it becomes a little clearer what's going on.
