### ISSUE TITLE
Make GitHub repo more amenable to user contributions

### ISSUE THREAD

**Issue by arosen93** [arosen93/QMOF#2]
Self-explanatory. As brought up by @kjappelbaum, the GitHub page should make it more seamless to fork and make PRs. Will need to navigate file size limits and should be kept small here, but nonetheless should have some of the curated data from the Figshare. Also provide instructions on how to contribute,

**Comment by kjappelbaum** [comment]
some ideas: 

- a "development version" of the CIFs on GitHub, where users will be able to make PRs to fix issues with structures or add structures (could be maybe organized in subfolders based on linker/metal/year/topology/[some id like they used for CURATED COFs](https://github.com/danieleongari/CURATED-COFs), or something like that makes it easier to navigate)
- one can set up some actions like https://github.com/danieleongari/CURATED-COFs/blob/master/.pre-commit-config.yaml to validate the CIFs, would be nice to extend this list of checks over time. 

I think it would be really great if one could keep evolving the database with the community. Someone (you? 😆) would still need to update the DFTs derived data, but that could be done for each release based on the changelog and you just point to new versions of files on figshare in the readme.

**Comment by arosen93** [comment]
Good ideas! Thanks for sharing!

One thing for me to think about is that I don't want this to necessarily be a structure repository because the parent CSD MOF subset (and CoRE MOF database) are both excellent at their jobs there. Ideally, any structural errors could be noted and actually updated [here](https://sites.google.com/view/csdmofsubset/home) for the CSD MOF subset or [here](https://zenodo.org/record/3677685) for the CoRE MOF database since then it's addressing the upstream repositories. 

Nonetheless, we all like clean data, so it's worth at the very least flagging potential issues here to help out future studies building off the QM/ML work in our initial paper. Lots of new data will be added to the QMOF database in the future, so if a user wishes to remove a file here or there, this will be a non-issue. I can also rerun the VASP calculations for a set of manually updated CIFs, although that's unfortunately not too sustainable a solution! Of course, others can do so as well. The ASE parameters are described in Table S2 of the SI.

Good things to think about.

**Comment by arosen93** [comment]
Thanks again for your helpful comments, @kjappelbaum. I just laid the groundwork for a possible contributing scheme, as described [here](https://github.com/arosen93/QMOF/tree/main/dev_changes). Very much a work in progress. Will keep this Issue open until I settle on a solid scheme.

**Comment by arosen93** [comment]
A barebones solution has now been set up, as described [here](https://github.com/arosen93/QMOF/tree/main/fidelity_tracker). It might be worth revisiting @kjappelbaum's excellent suggestions in the future, particularly with some actions to automatically validate CIFs. Currently, the minimal solution will have to do though.
