### ISSUE TITLE
List of CSD refcodes reference in the paper

### ISSUE THREAD

**Issue by flxmr** [arosen93/QMOF#31]
I am not able to find the "QMOF-42349"-intermediate dataset referenced in 10.1016/j.matt.2021.02.015 anywhere at figshare or in this repo. Maybe you could add a link to https://github.com/arosen93/QMOF/blob/main/data_sources.md (from where I gather this is not the full picture for the database anymore), as this might be useful!

Best

Felix

**Comment by arosen93** [comment]
Hi Felix,

It *should* be in the Figshare under the unoptimized structures folder. I
will confirm tomorrow and get back to you about specifics.

Andrew

**Comment by arosen93** [comment]
Hi @flxmr:

Please refer to `unrelaxed_structures.zip` and then `unrelaxed_structures/csd/gcd_files/QMOF-42349.gcd` in the Figshare repo.
