### ISSUE TITLE
process the MOF_data to get the file of opt-geometries.xyz

### ISSUE THREAD

**Issue by fei-wang-1314** [arosen93/QMOF#32]
Hi, how to process the MOF_data to get the file of opt-geometries.xyz?
Thank you.

**Comment by arosen93** [comment]
@fei-wang-1314: Thanks for asking. Since the original release of the QMOF Database, I have updated the files to be in a more accessible format (JSON and CIF). If you'd like to process the data to make a single .xyz file, simply do

```python
import os
from ase.io import read, write
p = '/path/to/cifs'
for cif in os.listdir(p):
    mofs.append(read(os.path.join(p,cif)))
write('opt-geometries.xyz',mofs)

**Comment by arosen93** [comment]
The data can be readily obtained from the JSON file provided in the Figshare repository. Pull out the data you'd like and simply convert it to csv. Unfortunately, I can't help with using someone else's code.

Alternatively, use an older version of the Figshare repository when the CSV files were still the way in which the data was disseminated.

**Comment by fei-wang-1314** [comment]
@arosen93 Thank you very much. According to your help, I have found the band gap file at 'https://figshare.com/articles/dataset/Ensemble_Band_Gap_Data/8295503?file=15544181'
For the two files:  
```
  mofs = ase.io.read('opt-geometries.xyz',index=':')
  refcodes = np.genfromtxt('opt-refcodes.csv',delimiter=',',dtype=str)
```
using the file：cifs_to_xyz.py at this repo.
